services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: wallets-tracking-app
    container_name: wallets-tracking-app-container
    ports:
      - "8080:8000"